# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField()),
                ('message_recieved', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('comments', 'Comments'), ('concerns', 'Concerns'), ('other', 'Other'), ('questions', 'Questions')], default='comments', max_length=120)),
                ('message_status', models.CharField(choices=[('answered', 'Answered'), ('recieved', 'Recieved'), ('responded', 'Responded')], default='recieved', max_length=120)),
            ],
        ),
    ]
