# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ImageField(null=True, upload_to='attachments'),
        ),
    ]
