# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to=products.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_to),
        ),
    ]
