# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_mainimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainimg',
            new_name='main_img',
        ),
    ]
