# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160330_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used - like new', 'Used - Like New'), ('used - very good', 'Used - Very Good'), ('used - good', 'Used - Good'), ('used - acceptable', 'Used - Acceptable')], max_length=120, null=True),
        ),
    ]
